### ISSUE TITLE
Drop `c_compiler_version` from build config

### ISSUE THREAD

**Issue by charlesbluca** [conda-forge/dask-sql-feedstock#64]
### Comment:

Don't think we have need for a specific C compiler version on any platform, so we should be good to remove the version specification on the next release since it creates some issues on Windows builds

**Comment by h-vetinari** [comment]
This is especially true because
https://github.com/conda-forge/dask-sql-feedstock/blob/4ec2ca4dbe6b95fcaa20e9bb20184d4fca1f6824/recipe/conda_build_config.yaml#L1-L3
will not do what you want it to do on windows (`c_compiler_version` is not used on windows, it's only possible to change the whole toolchain, e.g. `c_compiler` can be `vs2019` or `vs2022`).
